---
title: 'bike_type'
output: github_document
date: "2025-11-12"
---

```{r}
library(tidyverse)
library(lubridate)
```

# Import data
```{r}
data <- read_csv("citibike_sample_12k.csv")
```


# Data Preprocessing
```{r}
# Calculate ride duration in minutes
data =
  data |>
  mutate(
    started_at = ymd_hms(started_at),
    ended_at = ymd_hms(ended_at),
    duration_min = as.numeric(difftime(ended_at, started_at, units = "mins")),
    month = floor_date(started_at, "month"),
    month_label = format(started_at, "%Y-%m")
  ) |>
   filter(year(started_at) == 2024)

# Filter out anomalies (duration between 0 and 200 minutes)
data_clean =
  data |>
  filter(duration_min > 0 & duration_min < 200)
```


# Bike Type Comparison: Usage and Duration

## Monthly statistics
```{r}
monthly_stats =
  data_clean |>
  group_by(month_label, rideable_type) |>
  summarize(
    ride_count = n(),                              
    total_duration = sum(duration_min),            
    avg_duration = mean(duration_min),             
    total_duration_hours = total_duration / 60,
    .groups = "drop"
  ) |>
  arrange(month_label)

monthly_stats
```

## Total Rides Comparison
```{r}
total_ride =
  monthly_stats |>
  ggplot(
    aes(x = month_label, y = ride_count, 
        fill = rideable_type)) +
  geom_col(position = position_dodge()) +
  geom_text(aes(label = ride_count),
            vjust = -0.5, 
            size = 3.5) +
  labs(
    title = "Monthly Ride Count Comparison by Bike Type",
    x = "Month",
    y = "Total Number of Rides",
    fill = "Bike Type"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "top"
  )

total_ride
```

## Average Duration Comparison
```{r}
avg_duration = 
  monthly_stats |>
  ggplot(
    aes(x = month_label, y = avg_duration,
        color = rideable_type, group = rideable_type)) +
    geom_line(linewidth = 1.2) +
    geom_point(size = 3) +
    geom_text(aes(label = round(avg_duration, 1)), 
              vjust = -1, 
              size = 5,
              show.legend = FALSE) +
    labs(
      title = "Average Ride Duration Comparsion by Bike Type",
      x = "Month",
      y = "Average Duration (minutes)",
      color = "Bike Type"
    ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "top"
    )

avg_duration
```

## Market Share Trend Comparison
```{r}
mkt_share =
  data_clean |>
  group_by(month_label, rideable_type) |>
  summarize(ride_count = n(), .groups = "drop") |>
  group_by(month_label) |>
  mutate(
    total = sum(ride_count),
    percentage = (ride_count / total) * 100
  ) |>
  ggplot(aes(x = month_label, y = percentage, 
             fill = rideable_type)) +
  geom_col(position = "stack") +
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_stack(vjust = 0.5),
            size = 3,
            color = "white",
            fontface = "bold") +
  labs(
    title = "Market Share Trend by Bike Type",
    x = "Month",
    y = "Percentage (%)",
    color = "Bike Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "top"
  ) +
  ylim(0, 100)

mkt_share
```


## User Type Preference
```{r}
user_bike_pref =
  data_clean |>
  group_by(member_casual, rideable_type) |>
  summarize(ride_count = n(), .groups = "drop") |>
  group_by(member_casual) |>
  mutate(
    percentage = (ride_count / sum(ride_count)) * 100
    ) |>
  ggplot(
    aes(x = member_casual, y = percentage, fill = rideable_type)) +
  geom_col(position = position_dodge()) +
  geom_text(aes(label = paste0(round(percentage, 1), "%")), 
            position = position_dodge(width = 0.9), 
            vjust = -0.5,
            size = 4) +
  labs(
    title = "Bike Type Preference by User Type",
    x = "User Type",
    y = "Percentage (%)",
    fill = "Bike Type"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "top"
  ) +
  ylim(0, 100)

user_bike_pref
```

## Ride Duration Distribution
```{r}
ride_dur = 
  data_clean |>
  ggplot(aes(x = duration_min, fill = rideable_type)) +
  geom_density(alpha = 0.5, linewidth = 1) +
  labs(
    title = "Ride Duration Density Distribution by Bike Type",
    x = "Duration (minutes)",
    y = "Density",
    fill = "Bike Type"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "top"
  ) +
  xlim(0, 50)

ride_dur
```


## Hourly Usage Pattern
```{r}
hourly_usage =
  data_clean |>
  mutate(hour = hour(started_at)) |>
  group_by(hour, rideable_type) |>
  summarize(ride_count = n(), .groups = "drop") |>
  mutate(time_label = sprintf("%02d:00", hour)) |>
  ggplot(aes(x = time_label, y = ride_count, 
            color = rideable_type, group = rideable_type)) +
  geom_line(linewidth = 1.2) +
  geom_point(size = 3) +
  labs(
    title = "Hourly Usage Pattern by Bike Type",
    x = "Hour of Day",
    y = "Number of Rides",
    color = "Bike Type"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "top"
  ) 

hourly_usage
```
