---
title: "membership"
author: "Mutian Li"
date: "2025-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
```


```{r}
data <- read_csv("data/citibike_sample_12k.csv")
```
```{r}
# Calculate ride duration in minutes
data =
  data |>
  mutate(
    started_at = ymd_hms(started_at),
    ended_at = ymd_hms(ended_at),
    duration_min = as.numeric(difftime(ended_at, started_at, units = "mins")),
    month = floor_date(started_at, "month"),
    month_label = format(started_at, "%Y-%m")
  ) |>
   filter(year(started_at) == 2024)

# Filter out anomalies (duration between 0 and 200 minutes)
data_clean =
  data |>
  filter(duration_min > 0 & duration_min < 200)
```


```{r}
glimpse(
  data_clean
)
```

## duration

```{r}
duration_monthly <- data_clean %>%
  group_by(month_label, member_casual) %>%
  summarise(
    avg_duration = mean(duration_min, na.rm = TRUE),
    median_duration = median(duration_min, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )

duration_monthly
```


```{r}
ggplot(duration_monthly, aes(
  x = month_label,
  y = avg_duration,
  color = member_casual,
  group = member_casual
)) +
  geom_line(size = 1.2) +
  geom_point(size = 2) +
  labs(
    title = "Monthly Average Ride Duration: Members vs Casual Riders",
    x = "Month",
    y = "Average Duration (minutes)",
    color = "User Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```



```{r}
ggplot(duration_monthly, aes(
  x = month_label,
  y = avg_duration,
  fill = member_casual
)) +
  geom_col(position = "dodge") +
  labs(
    title = "Average Ride Duration by Month: Members vs Casual Riders",
    x = "Month",
    y = "Average Duration (minutes)",
    fill = "User Type"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## counts

```{r}
count_monthly <- data_clean %>%
  group_by(month_label, member_casual) %>%
  summarise(
    ride_count = n(),
    .groups = "drop"
  )

count_monthly
```


```{r}
ggplot(count_monthly, aes(
  x = month_label,
  y = ride_count,
  fill = member_casual
)) +
  geom_col(position = "dodge") +
  labs(
    title = "Monthly Ride Counts: Members vs Casual Riders",
    x = "Month",
    y = "Number of Rides",
    fill = "User Type"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```



